process boxplot {
    publishDir "${params.outdir}/plots/", mode: "copy"
    input:
    path(test_metrics_files)
    path(script_boxplot)
    output:
    path("boxplot.png")
    script:
    """
    Rscript ${script_boxplot} ./
    """
    stub:
    """
    touch boxplot.png
    """
}


process roc_auc_curve {
    publishDir "${params.outdir}/plots/", mode: 'copy'
    input:
    path(test_predictions)
    path(script_roc_auc_curve)
    output:
    path("*.roc_auc_curve.png"), emit: roc_auc_curve
    script:
    // Output filename is auto-generated by R script as {feature_extractor}.{algorithm}.roc_auc_curve.png
    """
    Rscript ${script_roc_auc_curve} $test_predictions
    """
    stub:
    // Extract feature_extractor and algorithm from first file
    def parts = test_predictions[0].name.toString().split('\\.')
    def feature_extractor = parts[0]
    def algorithm = parts[1]
    """
    touch ${feature_extractor}.${algorithm}.roc_auc_curve.png
    """
}